-- Greenhouse + Lever job sources (58 boards)
-- Generated by: node scripts/ingestion/generate-ats-sources-sql.js
-- Apply in Supabase SQL Editor after create_jobs_tables.sql

INSERT INTO job_sources (id, slug, name, source_type, license, config, is_active, cron_interval_minutes)
VALUES
  (
    'a0000000-0000-4000-8000-000000000003',
    'gh-2u',
    '2U (Greenhouse)',
    'api',
    'Greenhouse Job Board API — https://boards-api.greenhouse.io',
    '{"provider":"greenhouse","board_token":"2u","company_name":"2U"}'::jsonb,
    true,
    180
  ),
  (
    'a0000000-0000-4000-8000-000000000004',
    'gh-akunacapital',
    'Akuna Capital (Greenhouse)',
    'api',
    'Greenhouse Job Board API — https://boards-api.greenhouse.io',
    '{"provider":"greenhouse","board_token":"akunacapital","company_name":"Akuna Capital"}'::jsonb,
    true,
    180
  ),
  (
    'a0000000-0000-4000-8000-000000000005',
    'gh-anthropic',
    'Anthropic (Greenhouse)',
    'api',
    'Greenhouse Job Board API — https://boards-api.greenhouse.io',
    '{"provider":"greenhouse","board_token":"anthropic","company_name":"Anthropic"}'::jsonb,
    true,
    180
  ),
  (
    'a0000000-0000-4000-8000-000000000006',
    'gh-asana',
    'Asana (Greenhouse)',
    'api',
    'Greenhouse Job Board API — https://boards-api.greenhouse.io',
    '{"provider":"greenhouse","board_token":"asana","company_name":"Asana"}'::jsonb,
    true,
    180
  ),
  (
    'a0000000-0000-4000-8000-000000000007',
    'gh-baidu',
    'Baidu (Greenhouse)',
    'api',
    'Greenhouse Job Board API — https://boards-api.greenhouse.io',
    '{"provider":"greenhouse","board_token":"baidu","company_name":"Baidu"}'::jsonb,
    true,
    180
  ),
  (
    'a0000000-0000-4000-8000-000000000008',
    'gh-brex',
    'Brex (Greenhouse)',
    'api',
    'Greenhouse Job Board API — https://boards-api.greenhouse.io',
    '{"provider":"greenhouse","board_token":"brex","company_name":"Brex"}'::jsonb,
    true,
    180
  ),
  (
    'a0000000-0000-4000-8000-000000000009',
    'gh-carta',
    'Carta (Greenhouse)',
    'api',
    'Greenhouse Job Board API — https://boards-api.greenhouse.io',
    '{"provider":"greenhouse","board_token":"carta","company_name":"Carta"}'::jsonb,
    true,
    180
  ),
  (
    'a0000000-0000-4000-8000-00000000000a',
    'gh-chime',
    'Chime (Greenhouse)',
    'api',
    'Greenhouse Job Board API — https://boards-api.greenhouse.io',
    '{"provider":"greenhouse","board_token":"chime","company_name":"Chime"}'::jsonb,
    true,
    180
  ),
  (
    'a0000000-0000-4000-8000-00000000000b',
    'gh-cloudflare',
    'Cloudflare (Greenhouse)',
    'api',
    'Greenhouse Job Board API — https://boards-api.greenhouse.io',
    '{"provider":"greenhouse","board_token":"cloudflare","company_name":"Cloudflare"}'::jsonb,
    true,
    180
  ),
  (
    'a0000000-0000-4000-8000-00000000000c',
    'gh-cockroachlabs',
    'Cockroach Labs (Greenhouse)',
    'api',
    'Greenhouse Job Board API — https://boards-api.greenhouse.io',
    '{"provider":"greenhouse","board_token":"cockroachlabs","company_name":"Cockroach Labs"}'::jsonb,
    true,
    180
  ),
  (
    'a0000000-0000-4000-8000-00000000000d',
    'gh-coinbase',
    'Coinbase (Greenhouse)',
    'api',
    'Greenhouse Job Board API — https://boards-api.greenhouse.io',
    '{"provider":"greenhouse","board_token":"coinbase","company_name":"Coinbase"}'::jsonb,
    true,
    180
  ),
  (
    'a0000000-0000-4000-8000-00000000000e',
    'gh-databricks',
    'Databricks (Greenhouse)',
    'api',
    'Greenhouse Job Board API — https://boards-api.greenhouse.io',
    '{"provider":"greenhouse","board_token":"databricks","company_name":"Databricks"}'::jsonb,
    true,
    180
  ),
  (
    'a0000000-0000-4000-8000-00000000000f',
    'gh-datadog',
    'Datadog (Greenhouse)',
    'api',
    'Greenhouse Job Board API — https://boards-api.greenhouse.io',
    '{"provider":"greenhouse","board_token":"datadog","company_name":"Datadog"}'::jsonb,
    true,
    180
  ),
  (
    'a0000000-0000-4000-8000-000000000010',
    'gh-discord',
    'Discord (Greenhouse)',
    'api',
    'Greenhouse Job Board API — https://boards-api.greenhouse.io',
    '{"provider":"greenhouse","board_token":"discord","company_name":"Discord"}'::jsonb,
    true,
    180
  ),
  (
    'a0000000-0000-4000-8000-000000000011',
    'gh-dropbox',
    'Dropbox (Greenhouse)',
    'api',
    'Greenhouse Job Board API — https://boards-api.greenhouse.io',
    '{"provider":"greenhouse","board_token":"dropbox","company_name":"Dropbox"}'::jsonb,
    true,
    180
  ),
  (
    'a0000000-0000-4000-8000-000000000012',
    'gh-duolingo',
    'Duolingo (Greenhouse)',
    'api',
    'Greenhouse Job Board API — https://boards-api.greenhouse.io',
    '{"provider":"greenhouse","board_token":"duolingo","company_name":"Duolingo"}'::jsonb,
    true,
    180
  ),
  (
    'a0000000-0000-4000-8000-000000000013',
    'gh-epicgames',
    'Epic Games (Greenhouse)',
    'api',
    'Greenhouse Job Board API — https://boards-api.greenhouse.io',
    '{"provider":"greenhouse","board_token":"epicgames","company_name":"Epic Games"}'::jsonb,
    true,
    180
  ),
  (
    'a0000000-0000-4000-8000-000000000014',
    'gh-figma',
    'Figma (Greenhouse)',
    'api',
    'Greenhouse Job Board API — https://boards-api.greenhouse.io',
    '{"provider":"greenhouse","board_token":"figma","company_name":"Figma"}'::jsonb,
    true,
    180
  ),
  (
    'a0000000-0000-4000-8000-000000000015',
    'gh-flexport',
    'Flexport (Greenhouse)',
    'api',
    'Greenhouse Job Board API — https://boards-api.greenhouse.io',
    '{"provider":"greenhouse","board_token":"flexport","company_name":"Flexport"}'::jsonb,
    true,
    180
  ),
  (
    'a0000000-0000-4000-8000-000000000016',
    'gh-gitlab',
    'GitLab (Greenhouse)',
    'api',
    'Greenhouse Job Board API — https://boards-api.greenhouse.io',
    '{"provider":"greenhouse","board_token":"gitlab","company_name":"GitLab"}'::jsonb,
    true,
    180
  ),
  (
    'a0000000-0000-4000-8000-000000000017',
    'gh-godaddy',
    'GoDaddy (Greenhouse)',
    'api',
    'Greenhouse Job Board API — https://boards-api.greenhouse.io',
    '{"provider":"greenhouse","board_token":"godaddy","company_name":"GoDaddy"}'::jsonb,
    true,
    180
  ),
  (
    'a0000000-0000-4000-8000-000000000018',
    'gh-hubspot',
    'HubSpot (Greenhouse)',
    'api',
    'Greenhouse Job Board API — https://boards-api.greenhouse.io',
    '{"provider":"greenhouse","board_token":"hubspot","company_name":"HubSpot"}'::jsonb,
    true,
    180
  ),
  (
    'a0000000-0000-4000-8000-000000000019',
    'gh-instacart',
    'Instacart (Greenhouse)',
    'api',
    'Greenhouse Job Board API — https://boards-api.greenhouse.io',
    '{"provider":"greenhouse","board_token":"instacart","company_name":"Instacart"}'::jsonb,
    true,
    180
  ),
  (
    'a0000000-0000-4000-8000-00000000001a',
    'gh-ionq',
    'IonQ (Greenhouse)',
    'api',
    'Greenhouse Job Board API — https://boards-api.greenhouse.io',
    '{"provider":"greenhouse","board_token":"ionq","company_name":"IonQ"}'::jsonb,
    true,
    180
  ),
  (
    'a0000000-0000-4000-8000-00000000001b',
    'gh-jetbrains',
    'JetBrains (Greenhouse)',
    'api',
    'Greenhouse Job Board API — https://boards-api.greenhouse.io',
    '{"provider":"greenhouse","board_token":"jetbrains","company_name":"JetBrains"}'::jsonb,
    true,
    180
  ),
  (
    'a0000000-0000-4000-8000-00000000001c',
    'gh-khanacademy',
    'Khan Academy (Greenhouse)',
    'api',
    'Greenhouse Job Board API — https://boards-api.greenhouse.io',
    '{"provider":"greenhouse","board_token":"khanacademy","company_name":"Khan Academy"}'::jsonb,
    true,
    180
  ),
  (
    'a0000000-0000-4000-8000-00000000001d',
    'gh-klaviyo',
    'Klaviyo (Greenhouse)',
    'api',
    'Greenhouse Job Board API — https://boards-api.greenhouse.io',
    '{"provider":"greenhouse","board_token":"klaviyo","company_name":"Klaviyo"}'::jsonb,
    true,
    180
  ),
  (
    'a0000000-0000-4000-8000-00000000001e',
    'gh-lattice',
    'Lattice (Greenhouse)',
    'api',
    'Greenhouse Job Board API — https://boards-api.greenhouse.io',
    '{"provider":"greenhouse","board_token":"lattice","company_name":"Lattice"}'::jsonb,
    true,
    180
  ),
  (
    'a0000000-0000-4000-8000-000000000020',
    'gh-lyft',
    'Lyft (Greenhouse)',
    'api',
    'Greenhouse Job Board API — https://boards-api.greenhouse.io',
    '{"provider":"greenhouse","board_token":"lyft","company_name":"Lyft"}'::jsonb,
    true,
    180
  ),
  (
    'a0000000-0000-4000-8000-000000000021',
    'gh-medium',
    'Medium (Greenhouse)',
    'api',
    'Greenhouse Job Board API — https://boards-api.greenhouse.io',
    '{"provider":"greenhouse","board_token":"medium","company_name":"Medium"}'::jsonb,
    true,
    180
  ),
  (
    'a0000000-0000-4000-8000-000000000022',
    'gh-mongodb',
    'MongoDB (Greenhouse)',
    'api',
    'Greenhouse Job Board API — https://boards-api.greenhouse.io',
    '{"provider":"greenhouse","board_token":"mongodb","company_name":"MongoDB"}'::jsonb,
    true,
    180
  ),
  (
    'a0000000-0000-4000-8000-000000000023',
    'gh-n26',
    'N26 (Greenhouse)',
    'api',
    'Greenhouse Job Board API — https://boards-api.greenhouse.io',
    '{"provider":"greenhouse","board_token":"n26","company_name":"N26"}'::jsonb,
    true,
    180
  ),
  (
    'a0000000-0000-4000-8000-000000000024',
    'gh-nextdoor',
    'Nextdoor (Greenhouse)',
    'api',
    'Greenhouse Job Board API — https://boards-api.greenhouse.io',
    '{"provider":"greenhouse","board_token":"nextdoor","company_name":"Nextdoor"}'::jsonb,
    true,
    180
  ),
  (
    'a0000000-0000-4000-8000-000000000025',
    'gh-nintendo',
    'Nintendo (Greenhouse)',
    'api',
    'Greenhouse Job Board API — https://boards-api.greenhouse.io',
    '{"provider":"greenhouse","board_token":"nintendo","company_name":"Nintendo"}'::jsonb,
    true,
    180
  ),
  (
    'a0000000-0000-4000-8000-000000000026',
    'gh-okta',
    'Okta (Greenhouse)',
    'api',
    'Greenhouse Job Board API — https://boards-api.greenhouse.io',
    '{"provider":"greenhouse","board_token":"okta","company_name":"Okta"}'::jsonb,
    true,
    180
  ),
  (
    'a0000000-0000-4000-8000-000000000027',
    'gh-optiver',
    'Optiver (Greenhouse)',
    'api',
    'Greenhouse Job Board API — https://boards-api.greenhouse.io',
    '{"provider":"greenhouse","board_token":"optiver","company_name":"Optiver"}'::jsonb,
    true,
    180
  ),
  (
    'a0000000-0000-4000-8000-000000000028',
    'gh-pagerduty',
    'PagerDuty (Greenhouse)',
    'api',
    'Greenhouse Job Board API — https://boards-api.greenhouse.io',
    '{"provider":"greenhouse","board_token":"pagerduty","company_name":"PagerDuty"}'::jsonb,
    true,
    180
  ),
  (
    'a0000000-0000-4000-8000-000000000029',
    'gh-peloton',
    'Peloton (Greenhouse)',
    'api',
    'Greenhouse Job Board API — https://boards-api.greenhouse.io',
    '{"provider":"greenhouse","board_token":"peloton","company_name":"Peloton"}'::jsonb,
    true,
    180
  ),
  (
    'a0000000-0000-4000-8000-00000000002a',
    'gh-pinterest',
    'Pinterest (Greenhouse)',
    'api',
    'Greenhouse Job Board API — https://boards-api.greenhouse.io',
    '{"provider":"greenhouse","board_token":"pinterest","company_name":"Pinterest"}'::jsonb,
    true,
    180
  ),
  (
    'a0000000-0000-4000-8000-00000000002b',
    'gh-qualtrics',
    'Qualtrics (Greenhouse)',
    'api',
    'Greenhouse Job Board API — https://boards-api.greenhouse.io',
    '{"provider":"greenhouse","board_token":"qualtrics","company_name":"Qualtrics"}'::jsonb,
    true,
    180
  ),
  (
    'a0000000-0000-4000-8000-00000000002c',
    'gh-reddit',
    'Reddit (Greenhouse)',
    'api',
    'Greenhouse Job Board API — https://boards-api.greenhouse.io',
    '{"provider":"greenhouse","board_token":"reddit","company_name":"Reddit"}'::jsonb,
    true,
    180
  ),
  (
    'a0000000-0000-4000-8000-00000000002d',
    'gh-ripple',
    'Ripple (Greenhouse)',
    'api',
    'Greenhouse Job Board API — https://boards-api.greenhouse.io',
    '{"provider":"greenhouse","board_token":"ripple","company_name":"Ripple"}'::jsonb,
    true,
    180
  ),
  (
    'a0000000-0000-4000-8000-00000000002e',
    'gh-robinhood',
    'Robinhood (Greenhouse)',
    'api',
    'Greenhouse Job Board API — https://boards-api.greenhouse.io',
    '{"provider":"greenhouse","board_token":"robinhood","company_name":"Robinhood"}'::jsonb,
    true,
    180
  ),
  (
    'a0000000-0000-4000-8000-00000000002f',
    'gh-roblox',
    'Roblox (Greenhouse)',
    'api',
    'Greenhouse Job Board API — https://boards-api.greenhouse.io',
    '{"provider":"greenhouse","board_token":"roblox","company_name":"Roblox"}'::jsonb,
    true,
    180
  ),
  (
    'a0000000-0000-4000-8000-000000000030',
    'gh-roku',
    'Roku (Greenhouse)',
    'api',
    'Greenhouse Job Board API — https://boards-api.greenhouse.io',
    '{"provider":"greenhouse","board_token":"roku","company_name":"Roku"}'::jsonb,
    true,
    180
  ),
  (
    'a0000000-0000-4000-8000-000000000031',
    'gh-rubrik',
    'Rubrik (Greenhouse)',
    'api',
    'Greenhouse Job Board API — https://boards-api.greenhouse.io',
    '{"provider":"greenhouse","board_token":"rubrik","company_name":"Rubrik"}'::jsonb,
    true,
    180
  ),
  (
    'a0000000-0000-4000-8000-000000000032',
    'gh-samsara',
    'Samsara (Greenhouse)',
    'api',
    'Greenhouse Job Board API — https://boards-api.greenhouse.io',
    '{"provider":"greenhouse","board_token":"samsara","company_name":"Samsara"}'::jsonb,
    true,
    180
  ),
  (
    'a0000000-0000-4000-8000-000000000033',
    'gh-block',
    'Square (Greenhouse)',
    'api',
    'Greenhouse Job Board API — https://boards-api.greenhouse.io',
    '{"provider":"greenhouse","board_token":"block","company_name":"Square"}'::jsonb,
    true,
    180
  ),
  (
    'a0000000-0000-4000-8000-000000000034',
    'gh-squarespace',
    'Squarespace (Greenhouse)',
    'api',
    'Greenhouse Job Board API — https://boards-api.greenhouse.io',
    '{"provider":"greenhouse","board_token":"squarespace","company_name":"Squarespace"}'::jsonb,
    true,
    180
  ),
  (
    'a0000000-0000-4000-8000-000000000035',
    'gh-stitchfix',
    'Stitch Fix (Greenhouse)',
    'api',
    'Greenhouse Job Board API — https://boards-api.greenhouse.io',
    '{"provider":"greenhouse","board_token":"stitchfix","company_name":"Stitch Fix"}'::jsonb,
    true,
    180
  ),
  (
    'a0000000-0000-4000-8000-000000000036',
    'gh-stripe',
    'Stripe (Greenhouse)',
    'api',
    'Greenhouse Job Board API — https://boards-api.greenhouse.io',
    '{"provider":"greenhouse","board_token":"stripe","company_name":"Stripe"}'::jsonb,
    true,
    180
  ),
  (
    'a0000000-0000-4000-8000-000000000037',
    'gh-sumologic',
    'Sumo Logic (Greenhouse)',
    'api',
    'Greenhouse Job Board API — https://boards-api.greenhouse.io',
    '{"provider":"greenhouse","board_token":"sumologic","company_name":"Sumo Logic"}'::jsonb,
    true,
    180
  ),
  (
    'a0000000-0000-4000-8000-000000000038',
    'gh-twilio',
    'Twilio (Greenhouse)',
    'api',
    'Greenhouse Job Board API — https://boards-api.greenhouse.io',
    '{"provider":"greenhouse","board_token":"twilio","company_name":"Twilio"}'::jsonb,
    true,
    180
  ),
  (
    'a0000000-0000-4000-8000-000000000039',
    'gh-waymo',
    'Waymo (Greenhouse)',
    'api',
    'Greenhouse Job Board API — https://boards-api.greenhouse.io',
    '{"provider":"greenhouse","board_token":"waymo","company_name":"Waymo"}'::jsonb,
    true,
    180
  ),
  (
    'a0000000-0000-4000-8000-00000000003a',
    'gh-zscaler',
    'Zscaler (Greenhouse)',
    'api',
    'Greenhouse Job Board API — https://boards-api.greenhouse.io',
    '{"provider":"greenhouse","board_token":"zscaler","company_name":"Zscaler"}'::jsonb,
    true,
    180
  ),
  (
    'a0000000-0000-4000-8000-00000000003b',
    'lever-palantir',
    'Palantir (Lever)',
    'api',
    'Lever Postings API — https://api.lever.co',
    '{"provider":"lever","board_token":"palantir","company_name":"Palantir"}'::jsonb,
    true,
    180
  ),
  (
    'a0000000-0000-4000-8000-00000000003c',
    'lever-spotify',
    'Spotify (Lever)',
    'api',
    'Lever Postings API — https://api.lever.co',
    '{"provider":"lever","board_token":"spotify","company_name":"Spotify"}'::jsonb,
    true,
    180
  )
ON CONFLICT (slug) DO NOTHING;

