-- Expand companies lookup with top employers across major tech markets.
-- Run in Supabase SQL Editor after create_companies_table.sql

INSERT INTO companies (name) VALUES
  -- India
  ('Infosys'),
  ('Tata Consultancy Services'),
  ('Wipro'),
  ('HCL Technologies'),
  ('Tech Mahindra'),
  ('Flipkart'),
  ('Zomato'),
  ('Swiggy'),
  ('Ola'),
  ('Paytm'),
  ('Freshworks'),
  ('PhonePe'),
  ('CRED'),
  ('Meesho'),
  ('PolicyBazaar'),
  ('Nykaa'),
  ('Zoho'),
  ('MakeMyTrip'),
  ('Oyo'),
  ('Dream11'),
  ('InMobi'),
  ('BrowserStack'),
  ('Zepto'),
  ('Lenskart'),
  ('Urban Company'),
  ('Delhivery'),
  ('Slice'),

  -- United States (additional)
  ('Airbnb'),
  ('Affirm'),
  ('SoFi'),
  ('Twitch'),
  ('SpaceX'),
  ('Palantir Technologies'),
  ('Snowflake'),
  ('ServiceNow'),
  ('Workday'),
  ('Salesforce'),
  ('Uber'),
  ('DoorDash'),
  ('Netflix'),
  ('Tesla'),
  ('Nvidia'),
  ('OpenAI'),
  ('Notion'),
  ('Ramp'),
  ('Plaid'),
  ('HubSpot'),
  ('Grammarly'),
  ('Shopify'),
  ('Confluent'),
  ('HashiCorp'),
  ('Cruise'),
  ('Rivian'),
  ('Aurora'),
  ('NerdWallet'),
  ('Procore'),
  ('Miro'),
  ('Canva'),
  ('Autodesk'),
  ('Unity'),
  ('Yelp'),
  ('Box'),
  ('Atlassian'),

  -- United Kingdom
  ('Revolut'),
  ('Monzo'),
  ('Starling Bank'),
  ('Deliveroo'),
  ('ARM'),
  ('Wise'),
  ('Ocado'),
  ('ASOS'),
  ('Checkout.com'),
  ('Improbable'),
  ('Babylon Health'),
  ('Darktrace'),
  ('Skyscanner'),
  ('Farfetch'),
  ('BT Group'),
  ('Vodafone UK'),
  ('Google DeepMind'),

  -- France
  ('BlaBlaCar'),
  ('Criteo'),
  ('Doctolib'),
  ('Qonto'),
  ('Back Market'),
  ('Alan'),
  ('Mirakl'),
  ('Veepee'),
  ('Deezer'),
  ('Dassault Systèmes'),
  ('Capgemini'),
  ('Atos'),

  -- Germany
  ('Zalando'),
  ('Delivery Hero'),
  ('HelloFresh'),
  ('Celonis'),
  ('Personio'),
  ('Trade Republic'),
  ('Contentful'),
  ('TeamViewer'),
  ('Bosch'),
  ('BMW'),
  ('Porsche Digital'),

  -- Canada
  ('RBC'),
  ('TD Bank'),
  ('Scotiabank'),
  ('BMO'),
  ('Wealthsimple'),
  ('Hootsuite'),
  ('Lightspeed'),
  ('Coveo'),
  ('Clio'),
  ('Wattpad'),
  ('D2L'),
  ('Telus'),
  ('CGI'),

  -- Japan
  ('Rakuten'),
  ('Mercari'),
  ('LINE'),
  ('CyberAgent'),
  ('DeNA'),
  ('Recruit Holdings'),
  ('SoftBank'),
  ('Toyota'),
  ('Honda'),
  ('Fujitsu'),
  ('NTT Data'),
  ('Preferred Networks'),

  -- China
  ('Tencent'),
  ('JD.com'),
  ('Meituan'),
  ('Pinduoduo'),
  ('Xiaomi'),
  ('Huawei'),
  ('NetEase'),
  ('DJI'),
  ('Ant Group'),
  ('Lenovo'),
  ('BYD'),
  ('Bilibili'),
  ('Kuaishou'),

  -- Australia
  ('Afterpay'),
  ('Envato'),
  ('Culture Amp'),
  ('SafetyCulture'),
  ('Immutable'),
  ('Zip'),
  ('Tyro'),
  ('REA Group'),
  ('WiseTech Global'),

  -- New Zealand
  ('Xero'),
  ('Fisher & Paykel Healthcare'),
  ('Pushpay'),
  ('Rocket Lab'),
  ('Datacom'),
  ('Trade Me'),

  -- Singapore / broader APAC
  ('Grab'),
  ('Sea Limited'),
  ('Shopee'),
  ('Gojek'),
  ('Tokopedia'),
  ('Lazada')
ON CONFLICT (name) DO NOTHING;
