-- New Greenhouse / Lever job sources only (37 boards)
-- Skips slugs already present in prior greenhouse_lever migrations.
-- Generated by: node scripts/ingestion/generate-ats-sources-sql.js --expansion-only

INSERT INTO job_sources (slug, name, source_type, license, config, is_active, cron_interval_minutes)
VALUES
  (
    'gh-affirm',
    'Affirm (Greenhouse)',
    'api',
    'Greenhouse Job Board API — https://boards-api.greenhouse.io',
    '{"provider":"greenhouse","board_token":"affirm","company_name":"Affirm"}'::jsonb,
    true,
    180
  ),
  (
    'gh-airbnb',
    'Airbnb (Greenhouse)',
    'api',
    'Greenhouse Job Board API — https://boards-api.greenhouse.io',
    '{"provider":"greenhouse","board_token":"airbnb","company_name":"Airbnb"}'::jsonb,
    true,
    180
  ),
  (
    'gh-byd',
    'BYD (Greenhouse)',
    'api',
    'Greenhouse Job Board API — https://boards-api.greenhouse.io',
    '{"provider":"greenhouse","board_token":"byd","company_name":"BYD"}'::jsonb,
    true,
    180
  ),
  (
    'gh-celonis',
    'Celonis (Greenhouse)',
    'api',
    'Greenhouse Job Board API — https://boards-api.greenhouse.io',
    '{"provider":"greenhouse","board_token":"celonis","company_name":"Celonis"}'::jsonb,
    true,
    180
  ),
  (
    'gh-contentful',
    'Contentful (Greenhouse)',
    'api',
    'Greenhouse Job Board API — https://boards-api.greenhouse.io',
    '{"provider":"greenhouse","board_token":"contentful","company_name":"Contentful"}'::jsonb,
    true,
    180
  ),
  (
    'gh-cultureamp',
    'Culture Amp (Greenhouse)',
    'api',
    'Greenhouse Job Board API — https://boards-api.greenhouse.io',
    '{"provider":"greenhouse","board_token":"cultureamp","company_name":"Culture Amp"}'::jsonb,
    true,
    180
  ),
  (
    'gh-d2l',
    'D2L (Greenhouse)',
    'api',
    'Greenhouse Job Board API — https://boards-api.greenhouse.io',
    '{"provider":"greenhouse","board_token":"d2l","company_name":"D2L"}'::jsonb,
    true,
    180
  ),
  (
    'gh-deepmind',
    'Google DeepMind (Greenhouse)',
    'api',
    'Greenhouse Job Board API — https://boards-api.greenhouse.io',
    '{"provider":"greenhouse","board_token":"deepmind","company_name":"Google DeepMind"}'::jsonb,
    true,
    180
  ),
  (
    'gh-doctolib',
    'Doctolib (Greenhouse)',
    'api',
    'Greenhouse Job Board API — https://boards-api.greenhouse.io',
    '{"provider":"greenhouse","board_token":"doctolib","company_name":"Doctolib"}'::jsonb,
    true,
    180
  ),
  (
    'gh-farfetch',
    'Farfetch (Greenhouse)',
    'api',
    'Greenhouse Job Board API — https://boards-api.greenhouse.io',
    '{"provider":"greenhouse","board_token":"farfetch","company_name":"Farfetch"}'::jsonb,
    true,
    180
  ),
  (
    'gh-hellofresh',
    'HelloFresh (Greenhouse)',
    'api',
    'Greenhouse Job Board API — https://boards-api.greenhouse.io',
    '{"provider":"greenhouse","board_token":"hellofresh","company_name":"HelloFresh"}'::jsonb,
    true,
    180
  ),
  (
    'gh-hootsuite',
    'Hootsuite (Greenhouse)',
    'api',
    'Greenhouse Job Board API — https://boards-api.greenhouse.io',
    '{"provider":"greenhouse","board_token":"hootsuite","company_name":"Hootsuite"}'::jsonb,
    true,
    180
  ),
  (
    'gh-inmobi',
    'InMobi (Greenhouse)',
    'api',
    'Greenhouse Job Board API — https://boards-api.greenhouse.io',
    '{"provider":"greenhouse","board_token":"inmobi","company_name":"InMobi"}'::jsonb,
    true,
    180
  ),
  (
    'gh-mercari',
    'Mercari (Greenhouse)',
    'api',
    'Greenhouse Job Board API — https://boards-api.greenhouse.io',
    '{"provider":"greenhouse","board_token":"mercari","company_name":"Mercari"}'::jsonb,
    true,
    180
  ),
  (
    'gh-mirakl',
    'Mirakl (Greenhouse)',
    'api',
    'Greenhouse Job Board API — https://boards-api.greenhouse.io',
    '{"provider":"greenhouse","board_token":"mirakl","company_name":"Mirakl"}'::jsonb,
    true,
    180
  ),
  (
    'gh-monzo',
    'Monzo (Greenhouse)',
    'api',
    'Greenhouse Job Board API — https://boards-api.greenhouse.io',
    '{"provider":"greenhouse","board_token":"monzo","company_name":"Monzo"}'::jsonb,
    true,
    180
  ),
  (
    'gh-phonepe',
    'PhonePe (Greenhouse)',
    'api',
    'Greenhouse Job Board API — https://boards-api.greenhouse.io',
    '{"provider":"greenhouse","board_token":"phonepe","company_name":"PhonePe"}'::jsonb,
    true,
    180
  ),
  (
    'gh-pushpay',
    'Pushpay (Greenhouse)',
    'api',
    'Greenhouse Job Board API — https://boards-api.greenhouse.io',
    '{"provider":"greenhouse","board_token":"pushpay","company_name":"Pushpay"}'::jsonb,
    true,
    180
  ),
  (
    'gh-rocketlab',
    'Rocket Lab (Greenhouse)',
    'api',
    'Greenhouse Job Board API — https://boards-api.greenhouse.io',
    '{"provider":"greenhouse","board_token":"rocketlab","company_name":"Rocket Lab"}'::jsonb,
    true,
    180
  ),
  (
    'gh-skyscanner',
    'Skyscanner (Greenhouse)',
    'api',
    'Greenhouse Job Board API — https://boards-api.greenhouse.io',
    '{"provider":"greenhouse","board_token":"skyscanner","company_name":"Skyscanner"}'::jsonb,
    true,
    180
  ),
  (
    'gh-slice',
    'Slice (Greenhouse)',
    'api',
    'Greenhouse Job Board API — https://boards-api.greenhouse.io',
    '{"provider":"greenhouse","board_token":"slice","company_name":"Slice"}'::jsonb,
    true,
    180
  ),
  (
    'gh-sofi',
    'SoFi (Greenhouse)',
    'api',
    'Greenhouse Job Board API — https://boards-api.greenhouse.io',
    '{"provider":"greenhouse","board_token":"sofi","company_name":"SoFi"}'::jsonb,
    true,
    180
  ),
  (
    'gh-spacex',
    'SpaceX (Greenhouse)',
    'api',
    'Greenhouse Job Board API — https://boards-api.greenhouse.io',
    '{"provider":"greenhouse","board_token":"spacex","company_name":"SpaceX"}'::jsonb,
    true,
    180
  ),
  (
    'gh-tcs',
    'Tata Consultancy Services (Greenhouse)',
    'api',
    'Greenhouse Job Board API — https://boards-api.greenhouse.io',
    '{"provider":"greenhouse","board_token":"tcs","company_name":"Tata Consultancy Services"}'::jsonb,
    true,
    180
  ),
  (
    'gh-traderepublic',
    'Trade Republic (Greenhouse)',
    'api',
    'Greenhouse Job Board API — https://boards-api.greenhouse.io',
    '{"provider":"greenhouse","board_token":"traderepublic","company_name":"Trade Republic"}'::jsonb,
    true,
    180
  ),
  (
    'gh-twitch',
    'Twitch (Greenhouse)',
    'api',
    'Greenhouse Job Board API — https://boards-api.greenhouse.io',
    '{"provider":"greenhouse","board_token":"twitch","company_name":"Twitch"}'::jsonb,
    true,
    180
  ),
  (
    'lever-blablacar',
    'BlaBlaCar (Lever)',
    'api',
    'Lever Postings API — https://api.lever.co',
    '{"provider":"lever","board_token":"blablacar","company_name":"BlaBlaCar"}'::jsonb,
    true,
    180
  ),
  (
    'lever-cred',
    'CRED (Lever)',
    'api',
    'Lever Postings API — https://api.lever.co',
    '{"provider":"lever","board_token":"cred","company_name":"CRED"}'::jsonb,
    true,
    180
  ),
  (
    'lever-d2l',
    'D2L (Lever)',
    'api',
    'Lever Postings API — https://api.lever.co',
    '{"provider":"lever","board_token":"d2l","company_name":"D2L"}'::jsonb,
    true,
    180
  ),
  (
    'lever-farfetch',
    'Farfetch (Lever)',
    'api',
    'Lever Postings API — https://api.lever.co',
    '{"provider":"lever","board_token":"farfetch","company_name":"Farfetch"}'::jsonb,
    true,
    180
  ),
  (
    'lever-immutable',
    'Immutable (Lever)',
    'api',
    'Lever Postings API — https://api.lever.co',
    '{"provider":"lever","board_token":"immutable","company_name":"Immutable"}'::jsonb,
    true,
    180
  ),
  (
    'lever-meesho',
    'Meesho (Lever)',
    'api',
    'Lever Postings API — https://api.lever.co',
    '{"provider":"lever","board_token":"meesho","company_name":"Meesho"}'::jsonb,
    true,
    180
  ),
  (
    'lever-paytm',
    'Paytm (Lever)',
    'api',
    'Lever Postings API — https://api.lever.co',
    '{"provider":"lever","board_token":"paytm","company_name":"Paytm"}'::jsonb,
    true,
    180
  ),
  (
    'lever-qonto',
    'Qonto (Lever)',
    'api',
    'Lever Postings API — https://api.lever.co',
    '{"provider":"lever","board_token":"qonto","company_name":"Qonto"}'::jsonb,
    true,
    180
  ),
  (
    'lever-veepee',
    'Veepee (Lever)',
    'api',
    'Lever Postings API — https://api.lever.co',
    '{"provider":"lever","board_token":"veepee","company_name":"Veepee"}'::jsonb,
    true,
    180
  ),
  (
    'lever-wattpad',
    'Wattpad (Lever)',
    'api',
    'Lever Postings API — https://api.lever.co',
    '{"provider":"lever","board_token":"wattpad","company_name":"Wattpad"}'::jsonb,
    true,
    180
  )
ON CONFLICT (slug) DO NOTHING;

