-- New ATS job sources only (9 boards)
-- Skips slugs already present in prior migrations.
-- Generated by: node scripts/ingestion/generate-ats-sources-sql.js --expansion-only

INSERT INTO job_sources (slug, name, source_type, license, config, is_active, cron_interval_minutes)
VALUES
  (
    'ef-microsoft',
    'Microsoft (Eightfold)',
    'api',
    'Eightfold PCSX API — public career site JSON endpoints',
    '{"provider":"eightfold","company_name":"Microsoft","board_token":"microsoft","host":"microsoft","domain":"microsoft.com"}'::jsonb,
    true,
    180
  ),
  (
    'ef-nvidia',
    'Nvidia (Eightfold)',
    'api',
    'Eightfold PCSX API — public career site JSON endpoints',
    '{"provider":"eightfold","company_name":"Nvidia","board_token":"nvidia","host":"nvidia","domain":"nvidia.com"}'::jsonb,
    true,
    180
  ),
  (
    'ef-qualcomm',
    'Qualcomm (Eightfold)',
    'api',
    'Eightfold PCSX API — public career site JSON endpoints',
    '{"provider":"eightfold","company_name":"Qualcomm","board_token":"qualcomm","host":"qualcomm","domain":"qualcomm.com"}'::jsonb,
    true,
    180
  ),
  (
    'ef-paypal',
    'PayPal (Eightfold)',
    'api',
    'Eightfold PCSX API — public career site JSON endpoints',
    '{"provider":"eightfold","company_name":"PayPal","board_token":"paypal","host":"paypal","domain":"paypal.com"}'::jsonb,
    true,
    180
  ),
  (
    'ef-micron',
    'Micron (Eightfold)',
    'api',
    'Eightfold PCSX API — public career site JSON endpoints',
    '{"provider":"eightfold","company_name":"Micron","board_token":"micron","host":"micron","domain":"micron.com"}'::jsonb,
    true,
    180
  ),
  (
    'ef-vodafone',
    'Vodafone (Eightfold)',
    'api',
    'Eightfold PCSX API — public career site JSON endpoints',
    '{"provider":"eightfold","company_name":"Vodafone","board_token":"vodafone","host":"vodafone","domain":"vodafone.com"}'::jsonb,
    true,
    180
  ),
  (
    'ef-morganstanley',
    'Morgan Stanley (Eightfold)',
    'api',
    'Eightfold PCSX API — public career site JSON endpoints',
    '{"provider":"eightfold","company_name":"Morgan Stanley","board_token":"morganstanley","host":"morganstanley","domain":"morganstanley.com"}'::jsonb,
    true,
    180
  ),
  (
    'ef-starbucks',
    'Starbucks (Eightfold)',
    'api',
    'Eightfold PCSX API — public career site JSON endpoints',
    '{"provider":"eightfold","company_name":"Starbucks","board_token":"starbucks","host":"starbucks","domain":"starbucks.com"}'::jsonb,
    true,
    180
  ),
  (
    'ef-deloitte',
    'Deloitte (Eightfold)',
    'api',
    'Eightfold PCSX API — public career site JSON endpoints',
    '{"provider":"eightfold","company_name":"Deloitte","board_token":"deloitte","host":"deloitte","domain":"deloitte.de"}'::jsonb,
    true,
    180
  )
ON CONFLICT (slug) DO NOTHING;

