-- New ATS job sources only (19 boards)
-- Skips slugs already present in prior migrations.
-- Generated by: node scripts/ingestion/generate-ats-sources-sql.js --expansion-only

INSERT INTO job_sources (slug, name, source_type, license, config, is_active, cron_interval_minutes)
VALUES
  (
    'ashby-openai',
    'OpenAI (Ashby)',
    'api',
    'Ashby Job Postings API — https://api.ashbyhq.com/posting-api',
    '{"provider":"ashby","company_name":"OpenAI","board_token":"openai"}'::jsonb,
    true,
    180
  ),
  (
    'ashby-notion',
    'Notion (Ashby)',
    'api',
    'Ashby Job Postings API — https://api.ashbyhq.com/posting-api',
    '{"provider":"ashby","company_name":"Notion","board_token":"notion"}'::jsonb,
    true,
    180
  ),
  (
    'ashby-ramp',
    'Ramp (Ashby)',
    'api',
    'Ashby Job Postings API — https://api.ashbyhq.com/posting-api',
    '{"provider":"ashby","company_name":"Ramp","board_token":"ramp"}'::jsonb,
    true,
    180
  ),
  (
    'ashby-plaid',
    'Plaid (Ashby)',
    'api',
    'Ashby Job Postings API — https://api.ashbyhq.com/posting-api',
    '{"provider":"ashby","company_name":"Plaid","board_token":"plaid"}'::jsonb,
    true,
    180
  ),
  (
    'ashby-linear',
    'Linear (Ashby)',
    'api',
    'Ashby Job Postings API — https://api.ashbyhq.com/posting-api',
    '{"provider":"ashby","company_name":"Linear","board_token":"linear"}'::jsonb,
    true,
    180
  ),
  (
    'ashby-posthog',
    'PostHog (Ashby)',
    'api',
    'Ashby Job Postings API — https://api.ashbyhq.com/posting-api',
    '{"provider":"ashby","company_name":"PostHog","board_token":"posthog"}'::jsonb,
    true,
    180
  ),
  (
    'ashby-snowflake',
    'Snowflake (Ashby)',
    'api',
    'Ashby Job Postings API — https://api.ashbyhq.com/posting-api',
    '{"provider":"ashby","company_name":"Snowflake","board_token":"snowflake"}'::jsonb,
    true,
    180
  ),
  (
    'ashby-confluent',
    'Confluent (Ashby)',
    'api',
    'Ashby Job Postings API — https://api.ashbyhq.com/posting-api',
    '{"provider":"ashby","company_name":"Confluent","board_token":"confluent"}'::jsonb,
    true,
    180
  ),
  (
    'ashby-nerdwallet',
    'NerdWallet (Ashby)',
    'api',
    'Ashby Job Postings API — https://api.ashbyhq.com/posting-api',
    '{"provider":"ashby","company_name":"NerdWallet","board_token":"nerdwallet"}'::jsonb,
    true,
    180
  ),
  (
    'ashby-miro',
    'Miro (Ashby)',
    'api',
    'Ashby Job Postings API — https://api.ashbyhq.com/posting-api',
    '{"provider":"ashby","company_name":"Miro","board_token":"miro"}'::jsonb,
    true,
    180
  ),
  (
    'ashby-deliveroo',
    'Deliveroo (Ashby)',
    'api',
    'Ashby Job Postings API — https://api.ashbyhq.com/posting-api',
    '{"provider":"ashby","company_name":"Deliveroo","board_token":"deliveroo"}'::jsonb,
    true,
    180
  ),
  (
    'ashby-xero',
    'Xero (Ashby)',
    'api',
    'Ashby Job Postings API — https://api.ashbyhq.com/posting-api',
    '{"provider":"ashby","company_name":"Xero","board_token":"xero"}'::jsonb,
    true,
    180
  ),
  (
    'wd-nvidia',
    'Nvidia (Workday)',
    'api',
    'Workday CXS API — public career site JSON endpoints',
    '{"provider":"workday","company_name":"Nvidia","board_token":"nvidia","tenant":"nvidia","wd_server":"wd5","site":"NVIDIAExternalCareerSite"}'::jsonb,
    true,
    180
  ),
  (
    'wd-salesforce',
    'Salesforce (Workday)',
    'api',
    'Workday CXS API — public career site JSON endpoints',
    '{"provider":"workday","company_name":"Salesforce","board_token":"salesforce","tenant":"salesforce","wd_server":"wd12","site":"External_Career_Site"}'::jsonb,
    true,
    180
  ),
  (
    'wd-adobe',
    'Adobe (Workday)',
    'api',
    'Workday CXS API — public career site JSON endpoints',
    '{"provider":"workday","company_name":"Adobe","board_token":"adobe","tenant":"adobe","wd_server":"wd5","site":"external_experienced"}'::jsonb,
    true,
    180
  ),
  (
    'wd-workday',
    'Workday (Workday)',
    'api',
    'Workday CXS API — public career site JSON endpoints',
    '{"provider":"workday","company_name":"Workday","board_token":"workday","tenant":"workday","wd_server":"wd5","site":"Workday"}'::jsonb,
    true,
    180
  ),
  (
    'wd-accenture',
    'Accenture (Workday)',
    'api',
    'Workday CXS API — public career site JSON endpoints',
    '{"provider":"workday","company_name":"Accenture","board_token":"accenture","tenant":"accenture","wd_server":"wd103","site":"accenturecareers"}'::jsonb,
    true,
    180
  ),
  (
    'wd-intel',
    'Intel (Workday)',
    'api',
    'Workday CXS API — public career site JSON endpoints',
    '{"provider":"workday","company_name":"Intel","board_token":"intel","tenant":"intel","wd_server":"wd1","site":"External"}'::jsonb,
    true,
    180
  ),
  (
    'wd-capitalone',
    'Capital One (Workday)',
    'api',
    'Workday CXS API — public career site JSON endpoints',
    '{"provider":"workday","company_name":"Capital One","board_token":"capitalone","tenant":"capitalone","wd_server":"wd12","site":"Capital_One"}'::jsonb,
    true,
    180
  )
ON CONFLICT (slug) DO NOTHING;

