-- Create companies table for tech companies list
-- Run this in your Supabase SQL Editor

CREATE TABLE IF NOT EXISTS companies (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  name TEXT UNIQUE NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Insert popular tech companies (cleaned - removed duplicates)
INSERT INTO companies (name) VALUES
  ('1Password'),
  ('2U'),
  ('3M'),
  ('Accenture'),
  ('Adobe'),
  ('Akamai'),
  ('Akuna Capital'),
  ('Alibaba'),
  ('Alphabet (Google)'),
  ('Amazon'),
  ('AMD'),
  ('American Express'),
  ('Anthropic'),
  ('Aptiv'),
  ('Apple'),
  ('Argo AI'),
  ('Asana'),
  ('Atlassian'),
  ('Aurora'),
  ('Autodesk'),
  ('Baidu'),
  ('Bain & Company'),
  ('Bank of America'),
  ('Barclays'),
  ('BlackRock'),
  ('Bloomberg'),
  ('Booking.com'),
  ('Box'),
  ('Brex'),
  ('ByteDance (TikTok)'),
  ('Canva'),
  ('Capital One'),
  ('Carta'),
  ('Cerner'),
  ('Chime'),
  ('Cisco'),
  ('Citadel'),
  ('Citrix'),
  ('Cloudflare'),
  ('Cockroach Labs'),
  ('Coinbase'),
  ('Confluent'),
  ('Cruise'),
  ('Databricks'),
  ('Datadog'),
  ('Dell'),
  ('Deloitte'),
  ('Discord'),
  ('Docusign'),
  ('DoorDash'),
  ('Dropbox'),
  ('Duolingo'),
  ('eBay'),
  ('Epic Games'),
  ('Etsy'),
  ('Expedia'),
  ('F5 Networks'),
  ('Facebook (Meta)'),
  ('Fidelity'),
  ('Figma'),
  ('Flexport'),
  ('Foursquare'),
  ('Garmin'),
  ('General Electric'),
  ('GitHub'),
  ('GitLab'),
  ('Glassdoor'),
  ('GoDaddy'),
  ('Goldman Sachs'),
  ('Grab'),
  ('Grammarly'),
  ('Grubhub'),
  ('HashiCorp'),
  ('Hewlett Packard Enterprise'),
  ('Honeywell'),
  ('HubSpot'),
  ('Hulu'),
  ('IBM'),
  ('Indeed'),
  ('Instacart'),
  ('Intel'),
  ('Intuit'),
  ('IonQ'),
  ('JPMorgan Chase'),
  ('JetBrains'),
  ('Juniper Networks'),
  ('Khan Academy'),
  ('Klaviyo'),
  ('Lattice'),
  ('LendingClub'),
  ('LinkedIn'),
  ('Lime'),
  ('Loom'),
  ('Lululemon'),
  ('Lyft'),
  ('Mailchimp'),
  ('Marvell'),
  ('Mastercard'),
  ('McKinsey & Company'),
  ('Medium'),
  ('Mercedes-Benz'),
  ('Meta (Facebook)'),
  ('Microsoft'),
  ('Miro'),
  ('MongoDB'),
  ('Morgan Stanley'),
  ('Motorola'),
  ('N26'),
  ('NCR'),
  ('NerdWallet'),
  ('NetApp'),
  ('Netflix'),
  ('Nextdoor'),
  ('Nike'),
  ('Nintendo'),
  ('Nokia'),
  ('Notion'),
  ('Nutanix'),
  ('Nvidia'),
  ('Okta'),
  ('OpenAI'),
  ('Optiver'),
  ('Oracle'),
  ('PagerDuty'),
  ('Palantir'),
  ('Palo Alto Networks'),
  ('Patreon'),
  ('Paycom'),
  ('Paylocity'),
  ('PayPal'),
  ('Peloton'),
  ('Pinterest'),
  ('Plaid'),
  ('Postmates'),
  ('Procore'),
  ('Qualcomm'),
  ('Qualtrics'),
  ('Rackspace'),
  ('Ramp'),
  ('Rapid7'),
  ('Razorpay'),
  ('Red Hat'),
  ('Reddit'),
  ('Ripple'),
  ('Rivian'),
  ('Robinhood'),
  ('Roblox'),
  ('Roku'),
  ('Rubrik'),
  ('Salesforce'),
  ('Samsara'),
  ('Samsung'),
  ('SAP'),
  ('ServiceNow'),
  ('Shopify'),
  ('Siemens'),
  ('Slack'),
  ('Snapchat'),
  ('Snowflake'),
  ('Sony'),
  ('Splunk'),
  ('Spotify'),
  ('Square'),
  ('Squarespace'),
  ('Stitch Fix'),
  ('Stripe'),
  ('Sumo Logic'),
  ('Tableau'),
  ('Tesla'),
  ('TikTok'),
  ('Twilio'),
  ('Twitter (X)'),
  ('Uber'),
  ('Unity'),
  ('VMware'),
  ('Waymo'),
  ('Workday'),
  ('Yahoo'),
  ('Yelp'),
  ('Zoom'),
  ('Zscaler')
ON CONFLICT (name) DO NOTHING;

-- Create index for faster searches
CREATE INDEX IF NOT EXISTS idx_companies_name ON companies(name);

-- Verify the data
SELECT COUNT(*) as total_companies FROM companies;
